name: kinesis_py310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.3.1
      - clip==1.0
      - cloudpickle==3.1.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - easydict==1.11
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - filelock==3.20.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h5py==3.10.0
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-resources==6.4.5
      - iniconfig==2.3.0
      - ipdb==0.13.13
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - mujoco==3.1.2
      - networkx==3.4.2
      - numpy==1.21.6
      - numpy-stl==3.1.1
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==12.1.0
      - pluggy==1.6.0
      - promise==2.3
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyopengl==3.1.7
      - pyparsing==3.3.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - six==1.17.0
      - sk-video==1.1.10
      - smmap==5.0.2
      - smplx==0.1.28
      - stack-data==0.6.3
      - sympy==1.14.0
      - termcolor==2.4.0
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.66.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wandb==0.12.21
      - wcwidth==0.2.14
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/kinesis_py310
